spring.application.name=pokemon-codex-adapter

pokemon.api.base-url=https://pokeapi.co/api/v2
pokemon.api.paths.get-pokemon-info=/pokemon-species/{name}

translation.api.base-url=https://api.funtranslations.mercxry.me/v1
translation.api.paths.translate-yoda=/translate/yoda
translation.api.paths.translate-shakespeare=/translate/shakespeare
